name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: amatthew91/commitlint-github-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-lint-config: "github-action"
